import React,{useEffect,useState} from 'react';
import {api,setCsrf} from './api';
import {Card,Banner,useToast} from './ui';
import './cloud-social.css';

export function CloudAuth({onDone}:{onDone:()=>void}){
  const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[code,setCode]=useState('');
  const [busy,setBusy]=useState(false),[recovery,setRecovery]=useState(''),[saved,setSaved]=useState(false);const toast=useToast();
  async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{
    const r=await api.post<any>(`/api/auth/${mode}`,{email,password,displayName:name,code});
    if(r.csrfToken)setCsrf(r.csrfToken);
    if(r.recoveryCode){setRecovery(r.recoveryCode);setSaved(false);}else onDone();
  }catch(e:any){toast.push(e.message,'err');}finally{setBusy(false);}}
  return <main className="cloud-auth app-main"><div className="cloud-intro"><span className="eyebrow">A LITTLE EVERY DAY</span><h1 className="serif">让每一份努力，<br/>都有回响。</h1><p>随时学，换台设备接着学。<br/>与熟悉的朋友，一起积累属于自己的星光。</p><div className="cloud-seal">Lingo Scholar · 听词研习室</div></div><Card>
    {recovery?<div className="stack"><h2>请保存账号恢复码</h2><Banner kind="warn">没有邮件找回服务。忘记密码时需要邮箱和此恢复码；恢复码相当于钥匙，请勿发给好友。</Banner><code className="recovery-code">{recovery}</code><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(recovery);toast.push('恢复码已复制','ok');}catch{toast.push('请长按恢复码手动复制','info');}}}>复制恢复码</button><label className="row"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>我已保存到安全的地方</label><button className="btn primary" disabled={!saved} onClick={()=>{if(mode==='recover'){setRecovery('');setMode('login');setPassword('');setCode('');}else onDone();}}>{mode==='recover'?'返回登录':'开始学习'}</button></div>:<>
    <div className="pill-tabs"><button onClick={()=>setMode('login')} aria-pressed={mode==='login'}>登录</button><button onClick={()=>setMode('register')} aria-pressed={mode==='register'}>邮箱注册</button></div>
    <h2>{mode==='register'?'开启你的学习旅程':mode==='recover'?'使用恢复码找回':'欢迎回来'}</h2><p className="muted small">{mode==='register'?'注册即成功，不发送验证邮件。邮箱仅作登录标识，不代表身份已验证。':'使用同一邮箱登录，学习进度、收藏和星星自动从服务器加载。'}</p>
    <form className="stack" onSubmit={submit}><label className="field">邮箱<input className="input" type="email" required maxLength={254} autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label>
    {mode==='register'&&<label className="field">昵称<input className="input" required maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label>}
    {mode==='recover'&&<label className="field">恢复码<input className="input" required autoComplete="off" value={code} onChange={e=>setCode(e.target.value.trim())}/></label>}
    <label className="field">{mode==='recover'?'新密码':'密码'}<input className="input" type="password" required minLength={10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label><span className="tiny muted">至少 10 位，包含字母和数字。请勿复用其他网站密码。</span>
    <button className="btn primary wide" disabled={busy}>{busy?'请稍候…':mode==='register'?'创建账号':mode==='recover'?'重设密码':'进入研习室'}</button></form><button className="btn ghost" onClick={()=>setMode(mode==='recover'?'login':'recover')}>{mode==='recover'?'返回登录':'忘记密码？'}</button>
    </>}
  </Card></main>;
}

function Highlight({text,word}:{text:string;word:string}){const escaped=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return <>{text.split(new RegExp(`(${escaped})`,'gi')).map((part,i)=>part.toLowerCase()===word.toLowerCase()?<mark key={i}>{part}</mark>:part)}</>;}
export function SocialHub({reloadMe}:{reloadMe:()=>void}){
  const [data,setData]=useState<any>(null),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[challenge,setChallenge]=useState<any>(null),[feedback,setFeedback]=useState<any>(null),[scope,setScope]=useState('week');const toast=useToast();
  const load=()=>api.get('/api/social').then(setData).catch((e:any)=>toast.push(e.message,'err'));
  useEffect(()=>{load();},[]);
  async function action(fn:()=>Promise<any>){if(busy)return;setBusy(true);try{await fn();}catch(e:any){toast.push(e.message,'err');}finally{setBusy(false);}}
  const open=async(id:string)=>{setChallenge(await api.get(`/api/stars/challenges/${id}`));setFeedback(null);};
  if(challenge)return <div className="stack star-practice"><button className="btn ghost" onClick={()=>{setChallenge(null);load();reloadMe();}}>← 返回好友 · 进度自动保存</button><Card>
    <div className="row between"><span className="eyebrow">STAR CHALLENGE · 词义挑战</span><span>{Math.min(challenge.index+1,20)} / 20</span></div><progress className="star-progress" value={challenge.index} max={20}/>
    {feedback?<div className="stack" aria-live="polite"><h2>{feedback.correct?'答对了，记住它的语境。':'这次记住，下次会更熟悉。'}</h2><h1 className="serif">{feedback.word.lemma}</h1><p className="muted">/{feedback.word.phonetic}/</p><p style={{whiteSpace:'pre-line'}}>{feedback.word.meaningDisplay}</p><blockquote><Highlight text={feedback.word.example||''} word={feedback.word.lemma}/><p className="muted">{feedback.word.exampleZh}</p></blockquote><button className="btn primary" disabled={busy} onClick={()=>action(()=>open(challenge.id))}>继续 →</button></div>:challenge.result?<div className="star-result"><span>本组完成</span><h1>{challenge.result.stars>=0?'+':''}{challenge.result.stars} ★</h1><p>答对 {challenge.result.correct} / 20 · 正确率 {Math.round(challenge.result.accuracy*100)}%</p><p>当前共 {challenge.result.balance} 颗星星</p><button className="btn primary" onClick={()=>{setChallenge(null);load();reloadMe();}}>回到好友榜</button></div>:<><h1 className="serif challenge-word">{challenge.question.lemma}</h1><p className="muted" style={{textAlign:'center'}}>/{challenge.question.phonetic}/</p><div className="star-options">{challenge.question.options.map((o:any,i:number)=><button className="star-option" disabled={busy} key={o.id} onClick={()=>action(async()=>{const r=await api.post<any>(`/api/stars/challenges/${challenge.id}/answer`,{index:challenge.index,optionId:o.id});setFeedback(r.answer);reloadMe();})}><span>{'ABCD'[i]}</span><span>{o.text}</span></button>)}</div></>}
  </Card></div>;
  const board=[...(data?.board||[])].sort((a,b)=>b[scope]-a[scope]);
  return <div className="stack social-page"><section className="star-hero"><div><span className="eyebrow">GROW TOGETHER</span><h1>与好友，一起闪闪发光。</h1><p>比昨天更熟练，也比好友多一颗星。</p></div><div className="star-balance"><span>我的星星</span><strong>★ {data?.stars??'—'}</strong></div></section>
    <div className="social-grid"><Card><div className="row between"><h2>今日星星挑战</h2><span className="tag">20 词 / 组</span></div><p className="muted">每题第一次选择计分，服务器判定。退出不会扣星，换设备也能继续。</p><button className="btn primary wide" disabled={busy||!data||(!data.activeChallenge&&!data.remaining)} onClick={()=>action(async()=>{const r=await api.post<any>('/api/stars/challenges');await open(r.id);})}>{data?.activeChallenge?'继续未完成的挑战':`开启挑战 · 今日剩余 ${data?.remaining??'—'} 组`}</button><details className="star-rules"><summary>奖励和惩罚如何计算？</summary><p>95–100%：+10 ★；85–94%：+7 ★；70–84%：+4 ★；60–69%：+1 ★；低于 60%：−2 ★。总星星最低为 0。</p><p>每天最多 5 组，按北京时间换日。当天已抽过的词不重复计星；重复提交不重复结算。普通背词、拼写和听写不扣星。好友周榜周一重新统计，历史星星保留；本周净得星可能为负数。</p></details></Card>
    <Card><h2>通过邮箱添加好友</h2><form className="stack" onSubmit={e=>{e.preventDefault();action(async()=>{const r=await api.post<any>('/api/social/requests',{email});toast.push(r.message,'ok');setEmail('');await load();});}}><label className="field">好友邮箱<input className="input" type="email" required maxLength={254} placeholder="friend@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="btn" disabled={busy}>发送好友申请</button><p className="tiny muted">邮箱未经验证，请通过线下或聊天核对身份。接受后仅共享昵称和星星排名。</p></form></Card></div>
    {data?.friends.filter((f:any)=>f.status==='pending').map((f:any)=><Card key={f.id}><div className="row between"><span>{f.displayName} · {f.incoming?'申请添加你':'等待对方确认'}</span><div className="row">{f.incoming&&<button className="btn sm primary" disabled={busy} onClick={()=>action(async()=>{await api.post(`/api/social/requests/${f.id}`,{action:'accept'});await load();})}>接受</button>}<button className="btn sm" disabled={busy} onClick={()=>action(async()=>{await api.post(`/api/social/requests/${f.id}`,{action:'remove'});await load();})}>{f.incoming?'拒绝':'撤回'}</button></div></div></Card>)}
    <Card><div className="row between"><h2>好友星星榜</h2><div className="pill-tabs"><button aria-pressed={scope==='week'} onClick={()=>setScope('week')}>本周</button><button aria-pressed={scope==='total'} onClick={()=>setScope('total')}>累计</button></div></div><p className="tiny muted">只显示你和已确认的好友 · 同分并列 · 北京时间</p>{board.map((p:any,i:number)=>{const f=data.friends.find((f:any)=>f.userId===p.userId&&f.status==='accepted');return <div className="friend-row" key={p.userId}><span className="friend-rank">{board.findIndex((b:any)=>b[scope]===p[scope])+1}</span><span className="friend-name">{p.displayName}{!f?'（我）':''}</span><strong>★ {p[scope]}</strong>{f&&<button className="btn ghost sm" disabled={busy} onClick={()=>{if(window.confirm(`解除与 ${p.displayName} 的好友关系？`))action(async()=>{await api.post(`/api/social/requests/${f.id}`,{action:'remove'});await load();});}}>移除</button>}</div>;})}</Card></div>;
}
