import React,{useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions,type PDFDocumentProxy} from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=worker;
export function PdfReader({url,page,onPage,title}:{url:string;page:number;onPage:(n:number)=>void;title:string}){
 const [doc,setDoc]=useState<PDFDocumentProxy|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(true);
 const canvas=useRef<HTMLCanvasElement>(null);const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{setDoc(null);setError('');setBusy(true);let active=true;const task=getDocument({url});task.promise.then(d=>{if(active)setDoc(d);}).catch(()=>{if(active){setError('这份 PDF 暂时加载失败，请检查网络后重试。');setBusy(false);}});return()=>{active=false;void task.destroy();};},[url]);
 useEffect(()=>{if(!doc)return;let active=true;let render:any;setBusy(true);setError('');(async()=>{const p=await doc.getPage(Math.max(1,Math.min(doc.numPages,page)));if(!active||!canvas.current)return;const v=p.getViewport({scale:Math.min(2,((host.current?.clientWidth||700)-24)/p.getViewport({scale:1}).width)});const c=canvas.current;const ratio=Math.min(2,window.devicePixelRatio||1);c.width=v.width*ratio;c.height=v.height*ratio;c.style.width=`${v.width}px`;c.style.height=`${v.height}px`;render=p.render({canvas:c,canvasContext:c.getContext('2d')!,viewport:v,transform:[ratio,0,0,ratio,0,0]});await render.promise;const t=await p.getTextContent();if(active){setText(t.items.map((x:any)=>x.str||'').join(' '));setBusy(false);}})().catch(e=>{if(active&&e.name!=='RenderingCancelledException'){setError('此页渲染失败，可切换页面重试。');setBusy(false);}});return()=>{active=false;render?.cancel();};},[doc,page]);
 return <div ref={host} className="html-pdf-reader" aria-label={`${title}站内阅读器`}><div className="pdf-page-tools"><button className="btn" disabled={!doc||page<=1} onClick={()=>onPage(page-1)}>← 上一页</button><label>第 <input aria-label="PDF页码" type="number" min={1} max={doc?.numPages||1} value={page} onChange={e=>onPage(Math.max(1,Math.min(doc?.numPages||1,Number(e.target.value)||1)))}/> / {doc?.numPages||'…'} 页</label><button className="btn" disabled={!doc||page>=doc.numPages} onClick={()=>onPage(page+1)}>下一页 →</button></div>{busy&&<p role="status">正在加载页面…</p>}{error&&<p role="alert">{error}</p>}<canvas ref={canvas} aria-label={`${title} 第 ${page} 页`}/>{text&&<details><summary>本页文字（可选择复制）</summary><p className="pdf-page-text">{text}</p></details>}</div>;
}
