import React,{useEffect,useMemo,useRef,useState} from 'react';
import {api} from './api';
import {Bar,Skeleton,useAsync,useToast} from './ui';
import {FavoriteButton} from './favorites';
import {meaningChoices} from './choice-utils';
type Word={id:string;lemma:string;partOfSpeech:string;meaningZh:string;meaningDisplay?:string;phonetic?:string;phoneticLocale?:string;phoneticSource?:string;exampleZh?:string;acceptedSpellings?:string[];example?:string;exampleSource?:string;extra?:string;group:number;progress?:{familiarity:string;nextReviewAt:string}};
type Deck={id:string;title:string;shortTitle:string;description:string;wordCount:number;groupSize:number;words:Word[];progress?:{seen:number;due:number}};
const go=(route:string)=>{window.location.hash='#/'+route;};
function speak(text:string,locale='en-GB'){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=locale;u.rate=.85;speechSynthesis.speak(u);}
function Sentence({word}:{word:Word}){
 const {data}=useAsync<{translation:string}>(()=>api.get(`/api/study/word-translation/${word.id}`),[word.id],{immediate:!word.exampleZh});
 const variants=[...(word.acceptedSpellings||[]),word.lemma].filter(Boolean).sort((a,b)=>b.length-a.length);
 const pattern=variants.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');
 const parts=(word.example||'').split(new RegExp(`(${pattern})`,'ig'));
 return <section className="practice-context" aria-label="单词对应例句"><span>IN CONTEXT · 在句子中记住它</span><p className="serif">{parts.map((p,i)=>variants.some(v=>v.toLowerCase()===p.toLowerCase())?<mark key={i}>{p}</mark>:p)}</p><p className="sentence-translation">{word.exampleZh||data?.translation||'此例句暂无已核对译文'}</p><button className="btn sm" onClick={()=>speak(word.example||'')}>听完整例句</button>{word.extra&&word.extra!=='-'&&<p className="small">{word.extra}</p>}<small>{word.exampleSource} · 本地参考译文（含机器翻译）</small></section>;
}
export function VocabularyLibrary(){
 const {data,loading}=useAsync<{decks:Deck[];stats:{uniqueHeadwords:number}}>(()=>api.get('/api/resources/decks'),[]);
 const [query,setQuery]=useState('');
 if(loading||!data)return <Skeleton h={500}/>;
 return <div className="resource-page"><section className="resource-hero"><div className="resource-hero-copy"><span className="resource-overline">WORDS IN CONTEXT</span><h1>每一个词，都有它的语境。</h1><p>选词义、练拼写、听音默写。进度跟随账号，回来接着学。</p><input className="input" aria-label="搜索词库" placeholder="搜索主题词库" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="resource-hero-stats"><span><strong>{data.stats.uniqueHeadwords.toLocaleString()}</strong><small>去重词头 / 短语</small></span><span><strong>{data.decks.reduce((n,d)=>n+(d.progress?.due||0),0)}</strong><small>到期复习词条</small></span></div></section><p className="review-explainer">复习规则：答错 1 天后再练，答对 7 天后再练；旧版“模糊”记录为 3 天。进入词库选择“到期词”即可复习，这与正式课程计分复习分开。</p><div className="resource-grid">{data.decks.filter(d=>d.title.includes(query)).map((d,i)=><button className="resource-card vocab-book" key={d.id} onClick={()=>go(`resource-deck/${d.id}`)}><span className="eyebrow">WORD COLLECTION {String(i+1).padStart(2,'0')}</span><h2>{d.title}</h2><p>{d.description}</p><div className="deck-learning-progress"><Bar value={d.progress?.seen||0} max={d.wordCount}/><small>已学 {d.progress?.seen||0} / {d.wordCount} · {Math.round((d.progress?.seen||0)/d.wordCount*100)}%{Boolean(d.progress?.due)&&` · ${d.progress!.due} 词待复习`}</small></div><div className="resource-card-bottom"><strong>{d.wordCount} 词</strong><span>{d.progress?.seen?'继续学习':'开始学习'} →</span></div></button>)}</div></div>;
}
type Session={group:number;position:number;mode:'recall'|'spelling'|'dictation';filter:string;phase:'question'|'context';correct:boolean|null;queue:string[];selected?:string};
const initial:Session={group:1,position:0,mode:'recall',filter:'all',phase:'question',correct:null,queue:[]};
export function DailyVocabulary(){
 const {data,loading}=useAsync<{deckId:string;wordIds:string[];day:string}>(()=>api.get('/api/study/daily'),[]);
 if(loading||!data)return <Skeleton h={620}/>;
 return <><VocabularyPractice key={data.day} deckId={data.deckId} daily={data} onBack={()=>go('vocabulary')}/><button className="btn primary wide daily-practice-link" onClick={()=>go('vocabulary')}>进入词汇练习 · 选择我的主题词库 →</button></>;
}
export function VocabularyPractice({deckId,onBack,daily}:{deckId:string;onBack:()=>void;daily?:{wordIds:string[];day:string}}){
 const key=daily?`daily-practice:${daily.day}`:`practice:${deckId}`;
 const {data,loading}=useAsync<{deck:Deck;session:Session|null}>(async()=>{const [d,s]=await Promise.all([api.get<{deck:Deck}>(`/api/resources/decks/${deckId}?limit=1000`),api.get<{session:Session|null}>(`/api/study/session/${key}`)]);return {...d,...s};},[key]);
 const [state,setState]=useState<Session>(initial),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[answer,setAnswer]=useState('');
 const toast=useToast(),lock=useRef(false),input=useRef<HTMLInputElement>(null);
 const queueFor=(s:Session)=>data?.deck.words.filter(w=>(s.filter==='all'?w.group===s.group:true)&&(s.filter==='all'||(s.filter==='weak'?['again','fuzzy'].includes(w.progress?.familiarity||''):w.progress?.nextReviewAt&&Date.parse(w.progress.nextReviewAt)<=Date.now()))).map(w=>w.id)||[];
 useEffect(()=>{if(!data)return;let s=data.session||{...initial,queue:daily?.wordIds||data.deck.words.filter(w=>w.group===1).map(w=>w.id)};const requested=new URLSearchParams(window.location.hash.split('?')[1]).get('word');const w=data.deck.words.find(w=>w.id===requested);if(w&&!daily){const q=data.deck.words.filter(x=>x.group===w.group).map(x=>x.id);s={...initial,group:w.group,queue:q,position:q.indexOf(w.id)};}setState(s);setReady(true);},[data]);
 const words=useMemo(()=>state.queue.map(id=>data?.deck.words.find(w=>w.id===id)).filter(Boolean) as Word[],[data,state.queue]);
 const word=words[state.position];const choices=word?meaningChoices(word,data?.deck.words||[]):[];
 const save=async(next:Session)=>{await api.patch(`/api/study/session/${key}`,next);setState(next);setAnswer('');};
 const act=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);try{await action();}catch(e:any){toast.push(e.message||'保存失败，请重试','err');}finally{lock.current=false;setBusy(false);}};
 const choose=(ok:boolean,selected?:string)=>act(async()=>{if(!word||state.phase==='context')return;await api.patch(`/api/resources/decks/${deckId}/words/${word.id}`,{rating:ok?'known':'again'});await save({...state,phase:'context',correct:ok,selected});});
 const next=()=>act(()=>save({...state,position:state.position+1,phase:'question',correct:null,selected:undefined}));
 const change=(patch:Partial<Session>)=>act(async()=>{const s={...state,...patch,position:0,phase:'question' as const,correct:null,selected:undefined};await save({...s,queue:daily?.wordIds||queueFor(s)});});
 useEffect(()=>{if(state.mode!=='recall'&&state.phase==='question')input.current?.focus();},[state]);
 useEffect(()=>{const on=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,button,a')||busy||!word)return;if(state.phase==='context'&&(e.code==='Space'||e.key==='Enter')){e.preventDefault();next();}else if(state.mode==='recall'&&state.phase==='question'&&/^[1-4]$/.test(e.key)){e.preventDefault();const c=choices[Number(e.key)-1];if(c)choose(c.id===word.id,c.id);}};window.addEventListener('keydown',on);return()=>window.removeEventListener('keydown',on);});
 if(loading||!data||!ready)return <Skeleton h={640}/>;
 return <div className={`resource-deck-shell ${daily?'daily-vocabulary':''}`}><header className="resource-deck-head">{!daily&&<button onClick={onBack}>← 全部词库</button>}<div><span className="eyebrow">{daily?'DAILY WORDS · 每日词汇':'FOCUS / PRACTISE / REMEMBER'}</span><h1>{daily?'今天，记住 20 个词。':data.deck.title}</h1><p>{daily?`${data.deck.shortTitle} · 今日随机抽选，全天固定`:`${data.deck.wordCount} 词 · 自动保存练习位置`}</p></div></header>{!daily&&<div className="practice-toolbar"><div className="practice-modes">{([['recall','词义回想'],['spelling','看义拼写'],['dictation','听音默写']] as const).map(([k,label])=><button key={k} aria-pressed={state.mode===k} disabled={busy} onClick={()=>change({mode:k})}>{label}</button>)}</div><label>词组 <select className="input" value={state.group} disabled={busy||state.filter!=='all'} onChange={e=>change({group:Number(e.target.value)})}>{Array.from({length:Math.ceil(data.deck.wordCount/data.deck.groupSize)},(_,i)=><option key={i} value={i+1}>第 {i+1} 组</option>)}</select></label><label>范围 <select className="input" disabled={busy} value={state.filter} onChange={e=>change({filter:e.target.value})}><option value="all">全部词</option><option value="weak">薄弱词</option><option value="due">到期词</option></select></label></div>}
 <main className="context-stage" key={`${state.position}-${state.mode}-${state.group}`}>{!word?<div className="source-word-finished"><span className="eyebrow">SESSION COMPLETE</span><h2>{words.length?'这一组，记得更牢了。':'当前范围没有符合条件的词'}</h2><p>{words.length} 个词的学习记录已保存。</p>{!daily&&<button className="btn primary" disabled={busy} onClick={()=>change({group:state.group<Math.ceil(data.deck.wordCount/data.deck.groupSize)?state.group+1:1,filter:'all'})}>继续下一组</button>}<button className="btn" onClick={onBack}>选择其他主题</button></div>:<><div className="source-word-progress"><span>{state.mode.toUpperCase()}</span><Bar value={state.position} max={words.length}/><span>{state.position+1}/{words.length}</span></div><div className="context-word"><span className="eyebrow">{state.phase==='context'?'把词放回生活中':'选择完整、准确的词义'}</span><h2 className="serif">{state.phase==='context'||state.mode==='recall'?word.lemma:state.mode==='spelling'?(word.meaningDisplay||word.meaningZh):'听一听，写下来'}</h2>{(state.mode==='recall'||state.phase==='context')&&<p className="phonetic" title={word.phoneticSource}>{word.phonetic?`/${word.phonetic.replace(/^\/|\/$/g,'')}/`:'音标待补充'}</p>}{word.phoneticSource?.includes('规则')&&<small className="phonetic-source">规则生成 · 参考音标</small>}<div className="word-tools"><button className="word-pronounce" onClick={()=>speak(word.lemma,word.phoneticLocale==='US'?'en-US':'en-GB')}>◖ {word.phoneticLocale==='US'?'美式发音':'英式发音'}</button><FavoriteButton kind="word" id={`${deckId}:${word.id}`}/></div></div>
 {state.phase==='context'?<div className="context-feedback" aria-live="polite"><p className={state.correct?'correct':'incorrect'}>{state.correct?(state.mode==='recall'?'✓ 选择正确':'✓ 拼写正确'):'再记一次 · 正确答案：'+word.lemma}</p><p className="context-meaning">{word.meaningDisplay||word.meaningZh}</p><Sentence word={word}/><button className="btn primary wide" disabled={busy} onClick={next}>记住这个语境，继续 →</button></div>:state.mode==='recall'?<div className="meaning-options" aria-label="选择词义">{choices.map((c,i)=><button key={c.id} disabled={busy} onClick={()=>choose(c.id===word.id,c.id)}><span>{String.fromCharCode(65+i)}</span><strong>{c.meaningDisplay||c.meaningZh}</strong></button>)}</div>:<form className="practice-form" onSubmit={e=>{e.preventDefault();const norm=answer.trim().toLowerCase().replace(/\s+/g,' ');if(norm)choose([word.lemma,...word.acceptedSpellings||[]].some(s=>s.toLowerCase()===norm));}}><input ref={input} className="input answer-input" aria-label="拼写英文单词" value={answer} onChange={e=>setAnswer(e.target.value)} autoComplete="off" autoCapitalize="off" spellCheck={false} placeholder="输入英文单词"/><button className="btn primary wide" disabled={busy||!answer.trim()}>检查拼写</button><button className="btn wide" type="button" disabled={busy} onClick={()=>choose(false)}>想不起来，学习答案</button></form>}</>}</main></div>;
}
